#pragma once

#include <redasm/common.h>

// clang-format off
typedef enum RDThemeKind {
    THEME_DEFAULT = 0,
    THEME_FOREGROUND, THEME_BACKGROUND, THEME_SEEK,
    THEME_AUTOCOMMENT, THEME_COMMENT,
    THEME_HIGHLIGHTFG, THEME_HIGHLIGHTBG,
    THEME_SELECTIONFG, THEME_SELECTIONBG,
    THEME_CURSORFG, THEME_CURSORBG,
    THEME_SEGMENT, THEME_FUNCTION, THEME_TYPE,
    THEME_ADDRESS, THEME_CONSTANT, THEME_REG,
    THEME_STRING, THEME_LABEL, THEME_DATA, THEME_POINTER, THEME_IMPORT,
    THEME_NOP, THEME_RET, THEME_CALL, THEME_JUMP, THEME_JUMPCOND,
    THEME_ENTRYFG, THEME_ENTRYBG,
    THEME_GRAPHBG, THEME_GRAPHEDGE, THEME_GRAPHEDGELOOP, THEME_GRAPHEDGELOOPCOND,
    THEME_SUCCESS, THEME_FAIL, THEME_WARNING,
    THEME_COUNT,
} RDThemeKind;
// clang-format on

typedef const char** RDThemeColors;

REDASM_EXPORT bool rd_settheme(RDThemeKind kind, const char* color);
REDASM_EXPORT const char* rd_gettheme(RDThemeKind kind);
REDASM_EXPORT RDThemeColors rd_getfulltheme();
